### PR TITLE
Added executable bit (chmod a+x).

### PR DESCRIPTION
**Pull request by create3000**
I've done a 'chmod a+x' to make the file executable on unix/linux.

Can test the project with `npx . [args]`.

You must publish the project to NPM https://www.npmjs.com/search?q=x3dvalidate

Then you can do `npx x3dvalidate args`.

### CODE REVIEW

**Comment by coderextreme** [comment]
I got so excited to test publishing, I got put in a jail for 24 hours.

**Comment by create3000** [comment]
lol, but you won't get around publishing the package at NPM.

**Comment by coderextreme** [comment]
Well, I already tried it, and installed a package that didn't work, but
that would be amusing.

John

**Comment by create3000** [comment]
To NPM published, should be quite simple. Just make a `npm publish`.  You should of course always increase the version in package.json.

**Comment by coderextreme** [comment]
I "borrowed" your build/publish.pl script and modified it. Seems to work
okay.  I hope it's from a good source.

I did a "DOS attack" against the npm server, and they banned me from
publishing for 24 hours.


John

**Comment by create3000** [comment]
lol. Every time you publish to NPM you have to increment the version number of your project, then everything should work well.

**Comment by coderextreme** [comment]
Yes!

 I will try to publish soon!

John

**Comment by coderextreme** [comment]
I tried and tried.

x3dvalidate - npm (npmjs.com) <https://www.npmjs.com/package/x3dvalidate>

That's the best I can do without reading documentation

Thanks for any advice.

***@***.*** MINGW64 ~/tmp
$ npx ***@***.*** C:/Users/john/x3dvalidate/examples/*json
Need to install the following packages:
  ***@***.***
Ok to proceed? (y) y
The system cannot find the path specified.

C:\Users\john>npx x3dvalidate x3dvalidate\examples\*.json
The system cannot find the path specified.

C:\Users\john>npx x3dvalidate x3dvalidate\examples\abox.json
The system cannot find the path specified.

C:\Users\john>npx ***@***.*** x3dvalidate\examples\abox.json
The system cannot find the path specified.

C:\Users\john>npx

Entering npm script environment at location:
C:\Users\john
Type 'exit' or ^D when finished

Microsoft Windows [Version 10.0.19044.3086]
(c) Microsoft Corporation. All rights reserved.

**Comment by create3000** [comment]
I got the following error:

***@***.*** x_ite % npx x3dvalidate 
Need to install the following packages:
  ***@***.***
Ok to proceed? (y) 
node:internal/modules/cjs/loader:1051
  throw err;
  ^

Error: Cannot find module '/Users/holger/.npm/_npx/65ab09b9259d43f9/x3dvalidate/bin/x3dvalidate.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
    at Module._load (node:internal/modules/cjs/loader:901:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v20.4.0

Seems you have changed the bin in package.json, please try to revert to:

 "bin": {
    "x3dvalidate": "x3dvalidate.js"
  },

Why do you have an ‚electron‘ dependency: do you use it? In short: Electron is a BrowserWindow. But your script runs fine in plain node environment. If you remove electron install should go faster.

Holger Seelig
Leipzig, Germany

***@***.***
https://create3000.github.io/x_ite/

**Comment by coderextreme** [comment]
$ npx x3dvalidate
I see 0 parameters.  Is x3dvalidate installed properly?
Please specify some .json or .x3dj JSON filenames (any filename path) to
validate on the command-line, or in the validate/validateJSON function
call.  Full help is available via the --help command line option.

$ npx x3dvalidate examples/abox.json examples/rubik.json
I see 0 parameters.  Is x3dvalidate installed properly?
Please specify some .json or .x3dj JSON filenames (any filename path) to
validate on the command-line, or in the validate/validateJSON function
call.  Full help is available via the --help command line option.

$ npx . examples/abox.json examples/rubik.json
I see 0 parameters.  Is x3dvalidate installed properly?
Please specify some .json or .x3dj JSON filenames (any filename path) to
validate on the command-line, or in the validate/validateJSON function
call.  Full help is available via the --help command line option.
================================================
I can't publish currently.

I have started using a script similar to yours to publish:

build/publish.pl

Ran out of credits for today, no more publishes for 24 hours.

John

**Pull request merged**
